steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories describe search-restaurant-agent \
          --repository-format=docker \
          --location=asia-northeast1 || \
        gcloud artifacts repositories create search-restaurant-agent \
          --repository-format=docker \
          --location=asia-northeast1 \
          --description="Search Restaurant Agent container images"

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/search-restaurant-agent/app:$BUILD_ID'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/search-restaurant-agent/app:latest'
      - '.'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/search-restaurant-agent/app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'search-restaurant-agent'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/search-restaurant-agent/app:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '3600'
      - '--no-cpu-throttling'
      - '--execution-environment=gen2'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1,VERTEX_AI_PROJECT_ID=$PROJECT_ID,VERTEX_AI_LOCATION=asia-northeast1'
      - '--cpu-boost'

images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/search-restaurant-agent/app:$BUILD_ID
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/search-restaurant-agent/app:latest

options:
  logging: CLOUD_LOGGING_ONLY